apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-service-a
  labels:
    app: kube-service-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-service-a
  template:
    metadata:
      labels:
        app: kube-service-a
    spec:
      containers:
      - name: kube-service-a
        image: kube_cluster/service_a
        imagePullPolicy: Never
        ports:
          - containerPort: 3000