apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-web-nginx
  labels:
    app: kube-web-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-web-nginx
  template:
    metadata:
      labels:
        app: kube-web-nginx
    spec:
      containers:
        - name: kube-web-nginx
          image: kube_cluster/web-nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 3000