apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-web
  labels:
    app: kube-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-web
  template:
    metadata:
      labels:
        app: kube-web
    spec:
      containers:
      - name: kube-web
        image: kube_cluster/web
        imagePullPolicy: Never
        ports:
          - containerPort: 3000