apiVersion: v1
kind: Service
metadata:
  name: kube-web-service
spec:
  type: NodePort
  selector:
    app: kube-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000