apiVersion: v1
kind: Service
metadata:
  name: kube-web-nginx-service
spec:
  type: NodePort
  selector:
    app: kube-web-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001