apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  labels:
    name: redis-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      name: redis-replica
  template:
    metadata:
      labels:
        name: redis-replica
    spec:
      subdomain: replica
      containers:
        - name: redis
          image: redis:3.2.0
          command:
            - "redis-server"
          args:
            - "--slaveof"
#            - "primary.default.svc.cluster.local"
            - "redis-primary-service.default.svc.cluster.local"
            - "6379"
            - "--protected-mode"
            - "no"
          ports:
            - containerPort: 6379