apiVersion: v1
kind: Service
metadata:
  name: redis-primary-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
  selector:
    name: redis-primary